language: node_js
node_js: node
cache:
  directories:
  - node_modules
env:
- CI=true
deploy:
  provider: heroku
  api_key:
    secure: q+XXpI5qWCnU3ew6AD3zx0qJP+be3bkzWOuMPTUhgOjDQDPZDMuwKApCSb951VDCIiF3HFfPwltRt2NoGTHnpx2IgNJ6Kvcl81WUaB1SKyZIsMZp5hTQK2i5HOehwzgY7T5yitI2DHSSH8OYDP4QScullZQ+i6OPoDQUNulgjUSm/Jt1GL/LI/CZXsDsOXX4RKMtZ8hpKakEtKnHcyvVotMldHgsHwXmMegL+MhZtr2zkTZCdx/Cf1bxw3cDkQl/877ZiduXIUhLkCBpsJunmRLOugHeS13r39pzX14/piKbga8JWC5TQUudISIauAKosxZwO3coJMxW2n5lTe1AGaWeoS3bkAn5mo3K5XoJ2JlyptPu84w/BddwsbKQrTTuETOlDgAEuz/LaOvv7ZBZDsBzSqlte/hwSSjpck5z6v5AQXtbbioPsI8pAmEkBsq+UEbcSPyYhMIO6RYlv5c9enDZCk0FAsTVBi80AHFq88WQszVK9AiXeX4lYz5X7GEf+EBqZxIS2DqhsrlkgMwODKSPXmhsC3XX2mMsqezUWW+gvzePMc8nbU6I2FCsIaG0BIFL2ZHxCMkUrSmz+1iBFJVWTjWgb5h/e++j3fTyjm7obFmJg6Ll3jj6RXt8cFrVI05fltLQi120Y9djQT6WvxuVdAhQe6y4HitCCTbNkNQ=
  app: word-bound-helper
  on:
    repo: clintonowen/word-bound-helper
